import {StyleSheet} from 'react-native';

const typography = StyleSheet.create({
  hero: {
    fontFamily: 'nunito_bold',
    color: '#000000',
    fontSize: 54,
  },
  heading1: {
    fontSize: 32,
    fontFamily: 'nunito_bold',
    color: '#000000',
  },
  heading2: {
    fontSize: 28,
    color: '#000000',
    fontFamily: 'nunito_bold',
  },
  heading3: {
    color: '#000000',
    fontSize: 36,
    fontFamily: 'nunito_regular',
  },
  heading4: {
    fontSize: 28,
    fontFamily: 'nunito_regular',
  },
  heading4Bold: {
    fontSize: 24,
    fontFamily: 'nunito_regular',
    lineHeight: 32,
    fontWeight: '700',
  },
  heading5: {
    color: '#000000',
    fontSize: 24,
    fontFamily: 'nunito_regular',
    fontWeight: '500',
  },
  heading6: {
    fontSize: 18,
    fontFamily: 'nunito_regular',
  },
  heading3Bold: {
    color: '#000000',
    fontSize: 36,
    fontFamily: 'nunito_regular',
    fontWeight: '700',
    lineHeight: 40,
    paddingVertical: 12,
  },
  body1: {
    fontSize: 16,
    fontFamily: 'nunito_regular',
    fontWeight: '500',
  },
  body1Medium: {
    fontSize: 14,
    color: '#000000',
    fontFamily: 'nunito_medium',
  },
  body1Regular: {
    fontSize: 14,
    fontFamily: 'nunito_regular',
    color: '#000000',
  },
  body1Bold: {
    fontSize: 14,
    fontFamily: 'nunito_bold',
    fontWeight: '700',
    color: '#000000',
  },
  body2: {
    fontFamily: 'nunito_regular',
    fontSize: 16,
    lineHeight: 18,
    color: '#000000',
  },
  body2Bold: {
    fontFamily: 'nunito_bold',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 17,
    color: '#000000',
  },
  body2SemiBold: {
    fontFamily: 'nunito_semibold',
    fontSize: 16,
    color: '#000000',
  },
  body2Medium: {
    fontSize: 16,
    fontFamily: 'nunito_medium',
    color: '#000000',
  },
  body2Regular: {
    fontFamily: 'nunito_regular',
    fontSize: 16,
    color: '#000000',
  },
  button1Light: {
    fontSize: 18,
    fontFamily: 'nunito_light',
    lineHeight: 25,
    color: '#F3F3F3',
  },
  body3: {
    fontSize: 18,
    fontFamily: 'nunito_regular',
  },
  body3Regular: {
    fontFamily: 'nunito_regular',
    fontSize: 18,
    color: '#000000',
  },
  body3Medium: {
    fontFamily: 'nunito_medium',
    fontSize: 18,
    color: '#000000',
  },
  body3Bold: {
    fontFamily: 'nunito_bold',
    fontSize: 18,
    lineHeight: 21,
    color: '#000000',
    fontWeight: 'bold',
  },
  caption1: {
    color: '#000',
    fontSize: 12,
    fontFamily: 'nunito_regular',
  },
  caption1Regular: {
    fontSize: 12,
    fontFamily: 'nunito_regular',
    fontWeight: '400',
    lineHeight: 16,
  },
  caption1Medium: {
    fontSize: 13,
    fontFamily: 'nunito_regular',
    fontWeight: '500',
    lineHeight: 18,
  },
  caption2Medium: {
    fontSize: 15,
    fontFamily: 'nunito_regular',
    fontWeight: '500',
    lineHeight: 17,
  },
  caption2: {
    fontSize: 10,
    fontFamily: 'nunito_regular',
  },
  caption2regular: {
    fontSize: 10,
    fontFamily: 'nunito_regular',
    fontWeight: '400',
    lineHeight: 12,
  },
  caption2Bold: {
    fontSize: 10,
    fontFamily: 'nunito_regular',
    fontWeight: '700',
    lineHeight: 16,
  },
  link1: {
    fontSize: 14,
    fontFamily: 'nunito_regular',
    fontWeight: '500',
  },
  link2: {
    fontSize: 12,
    fontFamily: 'nunito_regular',
    fontWeight: '500',
  },
  buttonDefault: {
    fontSize: 16,
    fontFamily: 'nunito_regular',
  },
  buttonSmall: {
    fontSize: 14,
    fontFamily: 'nunito_regular',
    fontWeight: '500',
  },
  title1Bold: {
    fontSize: 14,
    fontWeight: 'bold',
    fontFamily: 'nunito_regular',
    lineHeight: 18,
  },
  title2Bold: {
    fontSize: 21,
    fontWeight: 'bold',
    fontFamily: 'nunito_bold',
    lineHeight: 30,
    color: '#000',
  },
  title2Medium: {
    fontSize: 18,
    fontWeight: '500',
    fontFamily: 'nunito_medium',
    lineHeight: 24,
  },
  button1Bold: {
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: 'nunito_regular',
    lineHeight: 24,
  },
  button2Bold: {
    fontSize: 14,
    fontWeight: 'bold',
    fontFamily: 'nunito_regular',
    lineHeight: 20,
  },
  button2Regular: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'nunito_regular',
    lineHeight: 20,
  },
  button1Medium: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'nunito_regular',
    lineHeight: 24,
  },
  button1Regular: {
    fontSize: 16,
    fontWeight: '400',
    fontFamily: 'nunito_regular',
    lineHeight: 20,
  },
  headline1: {
    fontFamily: 'nunito_regular',
    fontSize: 32,
    fontWeight: '700',
    lineHeight: 36,
    paddingVertical: 12,
    color: '#000000',
  },
  headline2: {
    fontFamily: 'nunito_regular',
    fontSize: 26,
    fontWeight: '700',
    lineHeight: 30,
    paddingVertical: 12,
  },
  headline3: {
    fontFamily: 'nunito_regular',
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 28,
    paddingVertical: 12,
  },
  headline4: {
    fontFamily: 'nunito_regular',
    fontSize: 22,
    fontWeight: '700',
    lineHeight: 26,
    paddingVertical: 12,
  },
  headline5: {
    fontFamily: 'nunito_regular',
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 24,
    paddingVertical: 12,
  },
  headline6: {
    fontFamily: 'nunito_regular',
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 22,
    paddingVertical: 12,
  },
  headline2Bold: {
    fontSize: 40,
    fontWeight: '700',
    lineHeight: 48,
    fontFamily: 'nunito_regular',
  },
  headline4Medium: {
    fontSize: 24,
    fontFamily: 'nunito_regular',
    fontWeight: '500',
    lineHeight: 32,
    letterSpacing: 0.5 / 100,
  },
  headline4Bold: {
    fontSize: 24,
    fontFamily: 'nunito_regular',
    fontWeight: '700',
    lineHeight: 32,
    letterSpacing: 0.005,
    textAlign: 'left',
  },
});

export const typographyWeight = StyleSheet.create({
  bold: {fontWeight: '700'},
  semibold: {fontWeight: '500'},
  extrabold: {fontWeight: '800'},
});

export default typography;
