export {default as IconCamera} from './IconCamera.png';
export {default as IconNotification} from './IconNotification.png';
export {default as IconChecked} from './IconChecked.png';
export {default as IconCheckedDone} from './IconCheckedDone.png';
export {default as IconCloudBackUp} from './IconCloudBackUp.png';
export {default as IconArrowRight} from './IconArrowRight.png';
export {default as IconManualBackUp} from './IconManualBackUp.png';
export {default as IconEyeActive} from './IconEyeActived.png';
export {default as IconEyeHided} from './IconEyeHiden.png';
